#!/bin/bash
# ══════════════════════════════════════════════════════════════════
#  deploy-to-dgx.sh — Command Base → NVIDIA DGX Spark Deployment
#  Run this from your Mac. It deploys the full stack to the DGX.
#  Generated by Onyx (CTO) — 2026-04-04
# ══════════════════════════════════════════════════════════════════
set -euo pipefail

# ── ⚙  CONFIGURE THESE BEFORE FIRST RUN ─────────────────────────
DGX_USER="${DGX_USER:-max}"
DGX_HOST="${DGX_HOST:-dgx-spark}"          # hostname, Tailscale name, or IP
DGX_SSH_KEY="${DGX_SSH_KEY:-}"             # optional: path to SSH key (e.g. ~/.ssh/id_dgx)
DGX_APP_DIR="/opt/command-base/app"
DGX_DATA_DIR="/opt/command-base/data"
DGX_SCRIPTS_DIR="/opt/command-base/scripts"

LOCAL_PROJECT_ROOT="/Users/maxstewart/Desktop/The Team"
LOCAL_APP_DIR="$LOCAL_PROJECT_ROOT/app"
LOCAL_DB="$LOCAL_PROJECT_ROOT/the_team.db"
LOCAL_DGX_PLANS_DIR="$LOCAL_APP_DIR/dgx-plans"

# ── Anthropic API key (required for Claude CLI fallback on DGX) ──
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
# ─────────────────────────────────────────────────────────────────

# ── Helpers ──────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }
hdr()  { echo -e "\n${CYAN}── $* ──${NC}"; }

SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 -o BatchMode=yes)
[[ -n "$DGX_SSH_KEY" ]] && SSH_OPTS+=(-i "$DGX_SSH_KEY")
SSH_E="ssh ${SSH_OPTS[*]}"
ssh_cmd() { ssh "${SSH_OPTS[@]}" "${DGX_USER}@${DGX_HOST}" "$@"; }

# ── Banner ────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║     Command Base — DGX Spark Deployment Script           ║"
printf "║     Target: %-44s║\n" "${DGX_USER}@${DGX_HOST}"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ══════════════════════════════════════════════════════════════════
# PHASE 1 — Pre-flight checks
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 1: Pre-flight checks"

[[ -f "$LOCAL_APP_DIR/server.js" ]] || { err "server.js not found at $LOCAL_APP_DIR"; exit 1; }
[[ -f "$LOCAL_DGX_PLANS_DIR/docker-compose.dgx.yml" ]] || { err "docker-compose.dgx.yml not found in $LOCAL_DGX_PLANS_DIR"; exit 1; }
[[ -f "$LOCAL_DGX_PLANS_DIR/Dockerfile.prod" ]] || { err "Dockerfile.prod not found in $LOCAL_DGX_PLANS_DIR"; exit 1; }
log "Local files OK"

[[ -f "$LOCAL_DB" ]] || { err "Database not found: $LOCAL_DB"; exit 1; }
DB_SIZE=$(du -sh "$LOCAL_DB" | cut -f1)
log "Database found: $DB_SIZE"

if ! ssh_cmd true 2>/dev/null; then
  err "Cannot SSH to ${DGX_USER}@${DGX_HOST}"
  echo "  Update DGX_USER / DGX_HOST at the top of this script."
  echo "  If using an SSH key: export DGX_SSH_KEY=~/.ssh/your_key"
  exit 1
fi
log "SSH to DGX: OK"

if ! ssh_cmd "docker info" &>/dev/null; then
  err "Docker is not running on DGX. Start Docker first."
  exit 1
fi
log "Docker on DGX: running"

if ssh_cmd "docker compose version" &>/dev/null 2>&1; then
  COMPOSE="docker compose"
else
  COMPOSE="docker-compose"
fi
log "Compose command: $COMPOSE"

command -v sqlite3 &>/dev/null || { err "sqlite3 not found locally: brew install sqlite"; exit 1; }
log "sqlite3 available locally"

# ══════════════════════════════════════════════════════════════════
# PHASE 2 — Create directory structure on DGX
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 2: Directory structure on DGX"

ssh_cmd "sudo mkdir -p \
  ${DGX_APP_DIR} \
  ${DGX_DATA_DIR}/db/backups \
  ${DGX_DATA_DIR}/uploads \
  ${DGX_DATA_DIR}/claude-config \
  ${DGX_DATA_DIR}/inbox \
  ${DGX_DATA_DIR}/outbox \
  ${DGX_SCRIPTS_DIR} && \
  sudo chown -R ${DGX_USER}:${DGX_USER} /opt/command-base && \
  sudo touch /var/log/command-base-backup.log && \
  sudo chmod 666 /var/log/command-base-backup.log"

log "Directories created at /opt/command-base"

# ══════════════════════════════════════════════════════════════════
# PHASE 3 — Safe database migration
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 3: Database migration"

# Stop local app for a clean WAL checkpoint
warn "Stopping local app (ports 3000/3001) to ensure clean DB snapshot..."
lsof -ti :3000 2>/dev/null | xargs kill -9 2>/dev/null || true
lsof -ti :3001 2>/dev/null | xargs kill -9 2>/dev/null || true
sleep 1

# sqlite3 .backup: performs a full WAL checkpoint into a clean single-file snapshot
BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOCAL_DB_BACKUP="/tmp/the_team_dgx_${BACKUP_TIMESTAMP}.db"

echo "  Creating WAL-checkpointed snapshot from: $LOCAL_DB"
sqlite3 "$LOCAL_DB" ".backup '$LOCAL_DB_BACKUP'"

INTEGRITY=$(sqlite3 "$LOCAL_DB_BACKUP" "PRAGMA integrity_check;" 2>&1)
if [[ "$INTEGRITY" != "ok" ]]; then
  err "Database integrity check failed: $INTEGRITY"
  rm -f "$LOCAL_DB_BACKUP"
  exit 1
fi
log "Snapshot integrity: OK ($(du -sh "$LOCAL_DB_BACKUP" | cut -f1))"

echo "  Transferring database to DGX..."
scp "${SSH_OPTS[@]}" "$LOCAL_DB_BACKUP" "${DGX_USER}@${DGX_HOST}:${DGX_DATA_DIR}/db/the_team.db"
rm -f "$LOCAL_DB_BACKUP"

# Verify on DGX
DGX_DB_INTEGRITY=$(ssh_cmd "sqlite3 ${DGX_DATA_DIR}/db/the_team.db 'PRAGMA integrity_check;' 2>&1")
[[ "$DGX_DB_INTEGRITY" == "ok" ]] || { err "DB integrity check FAILED on DGX: $DGX_DB_INTEGRITY"; exit 1; }
DGX_DB_SIZE=$(ssh_cmd "du -sh ${DGX_DATA_DIR}/db/the_team.db | cut -f1")
log "Database on DGX: $DGX_DB_SIZE (integrity: OK)"

# ══════════════════════════════════════════════════════════════════
# PHASE 4 — Transfer app files
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 4: App file transfer"

echo "  Rsyncing app files..."
rsync -avz --progress \
  -e "$SSH_E" \
  --exclude "node_modules/" \
  --exclude ".git/" \
  --exclude "*.db" \
  --exclude "*.db-shm" \
  --exclude "*.db-wal" \
  --exclude "backups/" \
  --exclude "test-output.log" \
  --exclude "audit-report.json" \
  --exclude "dashboard-audit.png" \
  --exclude "split-server.js" \
  --exclude "refactor-server.js" \
  --exclude "server.js.backup" \
  --exclude "server.js.pre-refactor-backup" \
  --exclude "server.js.ideas" \
  --exclude ".env.local" \
  --exclude "dgx-plans/" \
  --exclude ".playwright-mcp/" \
  "$LOCAL_APP_DIR/" \
  "${DGX_USER}@${DGX_HOST}:${DGX_APP_DIR}/"

log "App files transferred"

# Transfer Docker configs
scp "${SSH_OPTS[@]}" \
  "$LOCAL_DGX_PLANS_DIR/docker-compose.dgx.yml" \
  "${DGX_USER}@${DGX_HOST}:${DGX_APP_DIR}/docker-compose.yml"

scp "${SSH_OPTS[@]}" \
  "$LOCAL_DGX_PLANS_DIR/Dockerfile.prod" \
  "${DGX_USER}@${DGX_HOST}:${DGX_APP_DIR}/Dockerfile.prod"

log "Docker configs transferred"

# Transfer backup scripts (optional — non-fatal if missing)
for SCRIPT in backup-dgx.sh backup-weekly.sh verify-integrity.sh; do
  if [[ -f "$LOCAL_DGX_PLANS_DIR/$SCRIPT" ]]; then
    scp "${SSH_OPTS[@]}" "$LOCAL_DGX_PLANS_DIR/$SCRIPT" "${DGX_USER}@${DGX_HOST}:${DGX_SCRIPTS_DIR}/$SCRIPT"
  fi
done
ssh_cmd "chmod +x ${DGX_SCRIPTS_DIR}/*.sh 2>/dev/null || true"
log "Scripts transferred"

# Transfer Claude auth token if present
if [[ -f "$HOME/.claude.json" ]]; then
  scp "${SSH_OPTS[@]}" "$HOME/.claude.json" "${DGX_USER}@${DGX_HOST}:${DGX_DATA_DIR}/claude-config/.claude.json"
  log "Claude auth token transferred"
else
  warn "~/.claude.json not found — Claude CLI auth must be configured on DGX manually"
fi

# ══════════════════════════════════════════════════════════════════
# PHASE 5 — Write .env on DGX
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 5: Environment configuration"

ssh_cmd "cat > ${DGX_APP_DIR}/.env" << ENVEOF
# Command Base — DGX Spark Environment
# Generated by deploy-to-dgx.sh on ${BACKUP_TIMESTAMP}

# ── Core ──────────────────────────────────────────────────────────
NODE_ENV=production
PORT=3000
TRUST_PROXY=1

# ── Paths (match docker-compose.yml volume mounts) ────────────────
DB_PATH=/data/the_team.db
BACKUP_DIR=/data/backups
INBOX_PATH=/data/inbox
OUTBOX_PATH=/data/outbox

# ── Claude API key (fallback when local LLM unavailable) ──────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# ── Local LLM: Nemotron Cascade 2 via vLLM (port 8901) ───────────
# vLLM runs on DGX host. host.docker.internal resolves to host IP
# from inside the container (set via extra_hosts in docker-compose).
LOCAL_LLM_ENABLED=true
LOCAL_LLM_BASE_URL=http://host.docker.internal:8901/v1
LOCAL_LLM_MODEL=nvidia/Nemotron-Cascade-2-15B
LOCAL_LLM_TIMEOUT_MS=120000

# ── Spawn mode ────────────────────────────────────────────────────
# hybrid: Claude CLI for agentic/tool tasks, local LLM for text tasks
SPAWN_MODE=hybrid

# ── SQLite tuning for Linux ───────────────────────────────────────
DB_BUSY_TIMEOUT=10000
DB_CACHE_SIZE=-131072
DB_MMAP_SIZE=536870912
ENVEOF

log ".env written to ${DGX_APP_DIR}/.env"

# ══════════════════════════════════════════════════════════════════
# PHASE 6 — Build Docker image
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 6: Docker build"

echo "  Building image (ARM64 — compiles better-sqlite3 native addon)..."
echo "  First build takes 3–8 minutes..."
ssh_cmd "cd ${DGX_APP_DIR} && ${COMPOSE} build --no-cache 2>&1 | tail -15"
log "Docker image built"

# ══════════════════════════════════════════════════════════════════
# PHASE 7 — Start service
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 7: Start service"

ssh_cmd "cd ${DGX_APP_DIR} && ${COMPOSE} down --remove-orphans 2>/dev/null || true"
ssh_cmd "cd ${DGX_APP_DIR} && ${COMPOSE} up -d"
log "Container started"

# ══════════════════════════════════════════════════════════════════
# PHASE 8 — Health check
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 8: Health check"

echo "  Waiting for app to be ready (up to 60 seconds)..."
ATTEMPTS=0
until ssh_cmd "curl -sf http://localhost:3000/health" > /dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [[ $ATTEMPTS -ge 30 ]]; then
    err "Health check failed after 60 seconds"
    ssh_cmd "cd ${DGX_APP_DIR} && ${COMPOSE} logs --tail=50"
    exit 1
  fi
  printf "."
  sleep 2
done

echo ""
HEALTH=$(ssh_cmd "curl -sf http://localhost:3000/health 2>/dev/null")
log "Health check: PASSED"
echo "  $HEALTH"

# ══════════════════════════════════════════════════════════════════
# PHASE 9 — Verify Nemotron/vLLM
# ══════════════════════════════════════════════════════════════════
hdr "PHASE 9: Local LLM check"

if ssh_cmd "curl -sf http://localhost:8901/v1/models" > /dev/null 2>&1; then
  log "vLLM reachable at port 8901 on DGX host"
  if ssh_cmd "docker exec command-base curl -sf http://host.docker.internal:8901/v1/models" > /dev/null 2>&1; then
    log "vLLM reachable from inside container"
  else
    warn "vLLM on host but NOT from container — check extra_hosts in docker-compose.yml"
  fi
else
  warn "vLLM not running yet on port 8901 — app falls back to Claude API automatically"
  warn "  To start vLLM: see dgx-plans/nemotron-vllm-integration.md"
fi

# ══════════════════════════════════════════════════════════════════
# DONE
# ══════════════════════════════════════════════════════════════════
DGX_IP=$(ssh_cmd "hostname -I | awk '{print \$1}'")

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         Command Base is DEPLOYED and HEALTHY!            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  DGX local:     http://localhost:3000  (on DGX)"
echo "  DGX network:   http://${DGX_IP}:3000"
echo ""
echo "  Verify:  curl http://${DGX_IP}:3000/health"
echo ""
echo "Next steps:"
echo "  1. nginx reverse proxy:     dgx-plans/alloy-nginx-proxy.md (already in .claude/plans)"
echo "  2. Backups:                 dgx-plans/vigil-backup-strategy.md"
echo "  3. Monitoring:              dgx-plans/beacon-monitoring.md"
echo "  4. Start Nemotron/vLLM:     dgx-plans/nemotron-vllm-integration.md"
echo "  5. Claude CLI auth check:   docker exec command-base claude --version"
echo ""
