//! zkML proofs for AI recommendation provenance.
//!
//! Proves that AI recommendations were generated by a specific model
//! with specific confidence levels, without revealing model internals.

use exo_core::crypto::{hash_bytes, Blake3Hash};
use serde::{Deserialize, Serialize};

/// A zkML proof attesting to AI recommendation provenance.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AiProvenanceProof {
    pub model_hash: Blake3Hash,
    pub input_hash: Blake3Hash,
    pub output_hash: Blake3Hash,
    pub confidence_score: f64,
    pub proof_bytes: Vec<u8>,
    pub model_version: String,
}

/// zkML prover for AI provenance.
pub struct ZkMlProver;

impl ZkMlProver {
    /// Generate a provenance proof for an AI recommendation.
    pub fn prove_recommendation(
        model_hash: Blake3Hash,
        input_data: &[u8],
        output_data: &[u8],
        confidence: f64,
        model_version: String,
    ) -> AiProvenanceProof {
        let input_hash = hash_bytes(input_data);
        let output_hash = hash_bytes(output_data);

        let mut preimage = Vec::new();
        preimage.extend_from_slice(&model_hash.0);
        preimage.extend_from_slice(&input_hash.0);
        preimage.extend_from_slice(&output_hash.0);
        preimage.extend_from_slice(&confidence.to_le_bytes());
        let proof_bytes = hash_bytes(&preimage).0.to_vec();

        AiProvenanceProof {
            model_hash,
            input_hash,
            output_hash,
            confidence_score: confidence,
            proof_bytes,
            model_version,
        }
    }
}

impl AiProvenanceProof {
    /// Verify the provenance proof (stub).
    pub fn verify(&self) -> bool {
        !self.proof_bytes.is_empty() && self.confidence_score >= 0.0 && self.confidence_score <= 1.0
    }

    /// Check if confidence meets a minimum threshold.
    pub fn meets_confidence_threshold(&self, threshold: f64) -> bool {
        self.confidence_score >= threshold
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ai_provenance_proof() {
        let proof = ZkMlProver::prove_recommendation(
            Blake3Hash([1u8; 32]),
            b"input features",
            b"recommendation output",
            0.95,
            "governance-llm-v2".into(),
        );

        assert!(proof.verify());
        assert!(proof.meets_confidence_threshold(0.9));
        assert!(!proof.meets_confidence_threshold(0.99));
    }
}
