//! CGR Proof — cryptographic attestation that all invariants hold.
//!
//! A CGRProof is the kernel's signed output confirming a transition
//! preserves all constitutional invariants. Events marked PROVEN in the
//! spec require a valid CGRProof for finality.

use crate::invariants::{InvariantId, InvariantResult};
use exo_core::crypto::{hash_bytes, Blake3Hash};
use serde::{Deserialize, Serialize};

/// Status of a CGR proof.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofStatus {
    /// All invariants satisfied — transition may proceed.
    Valid,
    /// One or more invariants violated — transition REJECTED.
    Rejected,
}

/// A CGR Proof — the kernel's cryptographic attestation.
///
/// This is the output of the CGR Kernel's reduction process.
/// It attests that a proposed state transition satisfies all
/// constitutional invariants at the time of evaluation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CgrProof {
    /// Unique proof identifier.
    pub proof_id: u64,
    /// Whether this proof attests validity or rejection.
    pub status: ProofStatus,
    /// Number of invariants checked.
    pub invariants_checked: usize,
    /// Total reduction steps performed across all invariants.
    pub total_reduction_steps: u32,
    /// IDs of invariants that were evaluated.
    pub evaluated_invariants: Vec<String>,
    /// Content hash of the invariant registry used (INV-009 binding).
    pub registry_hash: Blake3Hash,
    /// Content hash of the kernel binary that produced this proof (INV-008 binding).
    pub kernel_hash: Blake3Hash,
    /// Timestamp of proof generation.
    pub timestamp_ms: u64,
    /// Content-addressed proof hash for verification.
    pub proof_hash: Blake3Hash,
}

impl CgrProof {
    /// Create a new valid proof from evaluation results.
    pub fn new(
        proof_id: u64,
        results: &[InvariantResult],
        registry_hash: &Blake3Hash,
        kernel_hash: &Blake3Hash,
        timestamp_ms: u64,
    ) -> Self {
        let all_satisfied = results.iter().all(|r| r.satisfied);
        let total_steps: u32 = results.iter().map(|r| r.reduction_steps).sum();
        let evaluated: Vec<String> = results.iter().map(|r| r.invariant_id.0.clone()).collect();

        let mut proof = Self {
            proof_id,
            status: if all_satisfied {
                ProofStatus::Valid
            } else {
                ProofStatus::Rejected
            },
            invariants_checked: results.len(),
            total_reduction_steps: total_steps,
            evaluated_invariants: evaluated,
            registry_hash: *registry_hash,
            kernel_hash: *kernel_hash,
            timestamp_ms,
            proof_hash: Blake3Hash([0u8; 32]),
        };
        proof.proof_hash = proof.compute_hash();
        proof
    }

    /// Compute content-addressed hash of this proof.
    pub fn compute_hash(&self) -> Blake3Hash {
        let mut data = Vec::new();
        data.extend_from_slice(b"EXOCHAIN-CGR-PROOF-v1:");
        data.extend_from_slice(&self.proof_id.to_le_bytes());
        data.push(match self.status {
            ProofStatus::Valid => 1,
            ProofStatus::Rejected => 0,
        });
        data.extend_from_slice(&(self.invariants_checked as u64).to_le_bytes());
        data.extend_from_slice(&self.total_reduction_steps.to_le_bytes());
        data.extend_from_slice(&self.registry_hash.0);
        data.extend_from_slice(&self.kernel_hash.0);
        data.extend_from_slice(&self.timestamp_ms.to_le_bytes());
        hash_bytes(&data)
    }

    /// Verify this proof's integrity — recompute hash and compare.
    pub fn verify_integrity(&self) -> bool {
        self.compute_hash() == self.proof_hash
    }

    /// Check that this proof covers a specific invariant.
    pub fn covers_invariant(&self, id: &InvariantId) -> bool {
        self.evaluated_invariants.iter().any(|i| *i == id.0)
    }

    /// Check that this proof was generated by a specific kernel version.
    pub fn from_kernel(&self, kernel_hash: &Blake3Hash) -> bool {
        self.kernel_hash == *kernel_hash
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_results() -> Vec<InvariantResult> {
        (1..=9)
            .map(|i| InvariantResult {
                invariant_id: InvariantId::new(&format!("INV-{:03}", i)),
                satisfied: true,
                reduction_steps: 1,
                message: "ok".to_string(),
            })
            .collect()
    }

    #[test]
    fn test_valid_proof_creation() {
        let results = make_results();
        let reg_hash = Blake3Hash([1u8; 32]);
        let kern_hash = Blake3Hash([2u8; 32]);
        let proof = CgrProof::new(1, &results, &reg_hash, &kern_hash, 1000);
        assert_eq!(proof.status, ProofStatus::Valid);
        assert_eq!(proof.invariants_checked, 9);
        assert_eq!(proof.total_reduction_steps, 9);
        assert!(proof.verify_integrity());
    }

    #[test]
    fn test_proof_hash_deterministic() {
        let results = make_results();
        let reg_hash = Blake3Hash([1u8; 32]);
        let kern_hash = Blake3Hash([2u8; 32]);
        let p1 = CgrProof::new(1, &results, &reg_hash, &kern_hash, 1000);
        let p2 = CgrProof::new(1, &results, &reg_hash, &kern_hash, 1000);
        assert_eq!(p1.proof_hash, p2.proof_hash);
    }

    #[test]
    fn test_proof_hash_changes_with_id() {
        let results = make_results();
        let reg_hash = Blake3Hash([1u8; 32]);
        let kern_hash = Blake3Hash([2u8; 32]);
        let p1 = CgrProof::new(1, &results, &reg_hash, &kern_hash, 1000);
        let p2 = CgrProof::new(2, &results, &reg_hash, &kern_hash, 1000);
        assert_ne!(p1.proof_hash, p2.proof_hash);
    }

    #[test]
    fn test_rejected_proof() {
        let mut results = make_results();
        results[0].satisfied = false;
        let proof = CgrProof::new(1, &results, &Blake3Hash([0u8; 32]), &Blake3Hash([0u8; 32]), 1000);
        assert_eq!(proof.status, ProofStatus::Rejected);
    }

    #[test]
    fn test_covers_invariant() {
        let results = make_results();
        let proof = CgrProof::new(1, &results, &Blake3Hash([0u8; 32]), &Blake3Hash([0u8; 32]), 1000);
        assert!(proof.covers_invariant(&InvariantId::new("INV-001")));
        assert!(proof.covers_invariant(&InvariantId::new("INV-009")));
        assert!(!proof.covers_invariant(&InvariantId::new("INV-999")));
    }

    #[test]
    fn test_from_kernel() {
        let results = make_results();
        let kern_hash = Blake3Hash([42u8; 32]);
        let proof = CgrProof::new(1, &results, &Blake3Hash([0u8; 32]), &kern_hash, 1000);
        assert!(proof.from_kernel(&kern_hash));
        assert!(!proof.from_kernel(&Blake3Hash([99u8; 32])));
    }

    #[test]
    fn test_tampered_proof_detected() {
        let results = make_results();
        let mut proof = CgrProof::new(1, &results, &Blake3Hash([0u8; 32]), &Blake3Hash([0u8; 32]), 1000);
        assert!(proof.verify_integrity());
        // Tamper
        proof.timestamp_ms = 9999;
        assert!(!proof.verify_integrity());
    }
}
